[versions]
aboutLibraries = "13.2.1"
android-buildTools = "36.1.0"
android-compileSdk = "36"
android-gradlePlugin = "8.13.2"
android-minSdk = "23"
android-targetSdk = "36"
androidx-activity = "1.12.4"
androidx-core = "1.17.0"
androidx-lifecycle = "2.10.0"
androidx-navigation3 = "1.0.1"
compose = "2026.02.00"
composePreference = "2.1.1"
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
okhttp3 = "5.3.2"
quickjs = "547f5b1597"

[libraries]
aboutLibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutLibraries" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-navigation3" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-material-materialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
composePreference = { group = "me.zhanghai.compose.preference", name = "preference", version.ref = "composePreference" }
kotlinx-serialization-json = { group="org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
quickjs-android = { group = "com.github.zhanghai.quickjs-java", name = "quickjs-android", version.ref = "quickjs" }

[plugins]
aboutLibraries-android = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
